# -*- coding: utf-8 -*-
"""day19_upsample2d_practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GJ89Mz7_YeM1BTSNk-srKuqxjGcgN1wZ
"""

import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, UpSampling2D
from tensorflow.keras import regularizers
import matplotlib.pyplot as plt
import numpy as np

"""### Defining a model using UpSampling2D -

"""

# Sample input data
X = np.asarray([[1, 2],
			      [3, 4]])
# Reshape the data
X = X.reshape((1, 2, 2, 1))

# Define model
model = Sequential()
# Upsample the data by a factor of 2
model.add(UpSampling2D(input_shape=(2, 2, 1)))
model.summary()

scaled_data = model.predict(X)
scaled_data = yhat.reshape((4, 4))
print(f"\n{yhat}")

